---
version: '3.8'

services:
  home-assistant:
    image: ${HOME_ASSISTANT_SERVICE_IMAGE:?}:${HOME_ASSISTANT_SERVICE_VERSION:?}
    container_name: ${HOME_ASSISTANT_SERVICE_NAME:?}
    ports:
      - "${HOME_ASSISTANT_SERVICE_PORT:?}:${HOME_ASSISTANT_INTERNAL_PORT:?}"
    environment:
      TZ: Europe/Vienna
    volumes:
      - ${DOCKER_DATA:?}/${HOME_ASSISTANT_SERVICE_NAME:?}:/config
      - ${DOCKER_DATA:?}/${HOME_ASSISTANT_SERVICE_NAME:?}/bumper-certs/custom_ca.pem:/usr/local/lib/python3.9/site-packages/certifi/cacert.pem:ro
    security_opt:
      - "label:disable"
    networks:
      - private
    privileged:
      true
    labels:
      traefik.enable: true
      traefik.http.routers.home-assistant-router.entrypoints: https
      traefik.http.routers.home-assistant-router.rule: Host(`${HOME_ASSISTANT_SERVICE_NAME:?}.${DOMAIN:?}`)
      traefik.http.routers.home-assistant-router.tls: true
      traefik.http.routers.home-assistant-router.tls.certresolver: letsEncrypt
      traefik.http.routers.home-assistant-router.service: ${HOME_ASSISTANT_SERVICE_NAME:?}-service
      traefik.http.services.home-assistant-service.loadbalancer.server.port: ${HOME_ASSISTANT_INTERNAL_PORT:?}
    restart: unless-stopped
